import React from 'react';
import { InlineMath } from 'react-katex';
import 'katex/dist/katex.min.css'; // Don't forget to import the CSS

/**
 * Helper function to strip common, non-semantic HTML tags 
 * often generated by DOCX conversion (mammoth) that interfere with plain text/KaTeX parsing.
 */
const stripCommonHtml = (htmlString) => {
    if (!htmlString) return "";
    
    let stripped = htmlString;
    // 1. Strip common bold/emphasis tags (<strong>, <b>, <em>, <i>)
    stripped = stripped.replace(/<\/?strong>/g, '');
    stripped = stripped.replace(/<\/?b>/g, '');
    stripped = stripped.replace(/<\/?em>/g, '');
    stripped = stripped.replace(/<\/?i>/g, '');
    stripped = stripped.replace(/<\/?span[^>]*>/g, ''); // Remove span tags if present
    
    // 2. Use DOMParser to safely decode HTML entities (like &lt; to <) if needed, 
    // although for KaTeX strings this might not be strictly necessary if the mammoth output is clean.
    // For safety, we rely on the string replacements above.
    return stripped;
};


// This component takes a text string (like the one saved in your database) 
// and renders the LaTeX parts inside $...$ as actual math.
const MathRenderer = ({ text }) => {
    if (!text) return null;

    // *** KEY FIX: Sanitize the text first to remove <strong> tags ***
    const sanitizedText = stripCommonHtml(text);
    
    // Regex to split the text by the math delimiters $...$
    // We keep the delimiters in the results using parentheses (non-capturing group)
    const parts = sanitizedText.split(/(\$[^\$]*\$)/g).filter(Boolean);

    return (
        <>
            {parts.map((part, index) => {
                // If the part starts and ends with $, it's a LaTeX string
                if (part.startsWith('$') && part.endsWith('$')) {
                    // Extract the math content without the dollar signs
                    const mathContent = part.substring(1, part.length - 1);
                    return <InlineMath key={index} math={mathContent} />;
                }
                // Otherwise, render it as plain text
                return <span key={index}>{part}</span>;
            })}
        </>
    );
};

export default MathRenderer;